const products = [
    {
      name: "Cinta de garbanzo con espinas y salsa de setas portobello",
      image: "https://content-cocina.lecturas.com/medio/2023/04/24/cintas_de_garbanzo_con_espinacas_y_salsa_de_setas_portobello_7f4208fc_1200x1200.jpg",
      description: "Esta exquisita cinta de garbanzo está acompañada de espinacas frescas y se sirve con una deliciosa salsa de setas portobello.",
      category: "Pastas",
      initial_price: 2700,
      discount: 0,
      final_price: 2700,
      status: true,
      total_score: 0,
    },
    {
      name: "Pasta de camarones y vino blanco",
      image: "https://www.cuerpomente.com/medio/2023/06/01/delicias-de-raviolis-de-maiz-con-relleno-de-setas-portobello-y-boletus-a-la-trufa_00000000_230601170012_1063x718.jpg",
      description: "Disfruta de una pasta deliciosa con camarones en una suave salsa de vino blanco.",
      category: "Pastas",
      initial_price: 2500,
      discount: 0,
      final_price: 2500,
      status: true,
      total_score: 0,
    },
    {
      name: "Delicia de Raviolis de maíz con relleno de setas portobello y boletus a la trufa",
      image: "https://www.cuerpomente.com/medio/2023/06/01/panzerotti-o-medialunas-de-arroz-con-relleno-de-pera-y-ricotta_00000000_230601103938_1063x717.jpg",
      description: "Los raviolis de maíz rellenos de setas portobello y boletus con un toque de trufa son una verdadera delicia.",
      category: "Pastas",
      initial_price: 2650,
      discount: 0,
      final_price: 2650,
      status: true,
      total_score: 0,
    },
    {
      name: "Panzerotti o medialunas de arroz con relleno de pera y ricotta",
      image: "https://www.cuerpomente.com/medio/2023/06/01/tallarines-de-trigo-sarraceno-integral-con-salsa-arrabbiata_00000000_230601103730_1063x718.jpg",
      description: "Estos panzerotti o medialunas de arroz son una delicia única con un sabroso relleno de pera y ricotta.",
      category: "Pastas",
      initial_price: 2200,
      discount: 0,
      final_price: 2200,
      status: true,
      total_score: 0,
    },
    {
      name: "Tallarines de trigo sarraceno integral con salsa arrabiata",
      image: "https://i.pinimg.com/originals/fe/85/84/fe858415fd0b3fa24f53ac9602d8c50b.jpg",
      description: "Los tallarines de trigo sarraceno integral se combinan perfectamente con una salsa arrabbiata sabrosa y ligeramente picante.",
      category: "Pastas",
      initial_price: 2250,
      discount: 0,
      final_price: 2250,
      status: true,
      total_score: 0,
    },
    {
      name: "Raviolones caseros",
      image: "https://image.freepik.com/foto-gratis/ravioles-hervidos-albahaca-queso-salsa-tomate-sobre-fondo-negro_118631-2338.jpg",
      description: "Deliciosos raviolones caseros sin TACC. Masa fina y relleno sabroso.",
      category: "Pastas",
      initial_price: 3100,
      discount: 0,
      final_price: 3100,
      status: true,
      total_score: 0,
    },
    {
      name: "Pasta con atún en salsa de chipotle",
      image: "https://www.lucchetti.com.mx/wp-content/uploads/2019/03/DESKTOP_MOBILE_imagenes_de_1024x683-5.png",
      description: "Pasta al dente con atún en salsa picante de chipotle. Sin TACC ni lactosa.",
      category: "Pastas",
      initial_price: 2950,
      discount: 0,
      final_price: 2950,
      status: true,
      total_score: 0,
    },
    {
      name: "Pasta rellena",
      image: "https://img-global.cpcdn.com/recipes/7041b21955686cf2/1360x964cq70/pasta-rellenas-sin-tacc-sin-gluten-vegan-foto-principal.webp",
      description: "Disfruta de una pasta exquisita y rellena con ingredientes frescos y sabrosos.",
      category: "Pastas",
      initial_price: 2600,
      discount: 0,
      final_price: 2600,
      status: true,
      total_score: 0,
    },
    {
      name: "Pasta con salteado de verduras",
      image: "https://img-global.cpcdn.com/recipes/6e877bb633a841aa/1360x964cq70/pastas-con-salteado-de-verduras-sin-gluten-foto-principal.webp",
      description: "Una deliciosa combinación de pasta y verduras salteadas que te brinda una experiencia culinaria llena de sabor y frescura.",
      category: "Pastas",
      initial_price: 2750,
      discount: 0,
      final_price: 2750,
      status: true,
      total_score: 0,
    },
];

module.exports = {
  products,
};


